# Generated by Django 3.1.1 on 2020-09-11 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='especialidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='medicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('crm', models.CharField(max_length=20, null=True)),
                ('certificado_especialidade', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='tipos_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Medico', 'Medico'), ('Cliente', 'Cliente')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.tipos_usuario')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='medicos_especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.especialidades')),
                ('id_medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.medicos')),
            ],
        ),
        migrations.AddField(
            model_name='medicos',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.tipos_usuario'),
        ),
        migrations.CreateModel(
            name='consultas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medicos_especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.medicos_especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='compras_consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.compras')),
                ('id_consulta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.consultas')),
            ],
        ),
        migrations.AddField(
            model_name='compras',
            name='id_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.pacientes'),
        ),
    ]
